# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a06d2c8d4b256c428eb68b33ccb798030bde2d09cfcc97a3f2e4f6026d5d23949046e07213249246da089efd276f71ce22b7647de58e0af1dbb48d9be6438f05

test:
  secret_key_base: 79ea9e204302f590d209711f5af3955088e5045b9b4767d4808d8520c0b6d890afc211d8cf76bd59e6459d6bd4a532fda58de8f25a5243a173973cece58944b2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
